before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: splat
    tap:
      owner: yalespinup
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    install: |
      bin.install "splat"
    license: AGPL
    folder: Formula
